### ISSUE TITLE
[Feature Request]: Improve metadata sync speed

### ISSUE THREAD

**Issue by sboesen** [sboesen/remotely-secure#13]
### What feature are you suggesting?

Step 4 of sync (fetching metadata from remote) takes a long time with larger vaults, per report by @YIRU69. Look into why this takes so long and try to improve this.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Somewhat related is the [issue](https://github.com/remotely-save/remotely-save/issues/372) filed on remotely-save, but it looks like this is [actually cleared periodically](https://github.com/sboesen/remotely-secure/blob/master/src/main.ts#L415).

It looks like the metadata is *just* [a list of deletions](https://github.com/sboesen/remotely-secure/blob/master/src/metadataOnRemote.ts#L22-L26) which have been synced to the remote, and each entry has a timestamp `actionWhen`.

Consider periodically deleting, similarly to the other cleanup function, and removing deletions which are over 30 days old.

Also consider adding a configuration option (or tracking this feature request separately) to set the frequency of cleaning these up.

**Comment by sboesen** [comment]
@YIRU69 are you still experiencing slow metadata sync? Might be harder to tell due to the sync status, but you can enable debug logging in the plugin settings to view the old sync notifications.

It should be a list of deletions, which unless you've deleted a lot of files shouldn't be that large of a file. Let me know if you think this is still an issue.

**Comment by YIRU69** [comment]
The speed look fine for my experiencing. You can close the issue.

**Comment by sboesen** [comment]
Thanks, closing!
