### ISSUE TITLE
[Feature Request]: Option to disable/shorten notifications

### ISSUE THREAD

**Issue by kadisonm** [sboesen/remotely-secure#15]
### What feature are you suggesting?

A setting to make notifications less intrusive.

An issue I have on IOS is that it floods the screen with multiple notifications when I am syncing. It would be nice to have a setting that minimises this into 'Syncing...' 'Complete' or 'Error' in under 2 notifications. However, still allowing users with the option to see more advanced information if they choose.

While the information is helpful when debugging an issue, in my everyday use when the plugin works the majority of the time I'd prefer not to see them.

'Remotely Secure already running in stage' could also be trimmed to 1 message or simplified. Maybe the ribbon icon could change to an X for a second to say it is already syncing and disable it completely? I noticed that sync on save triggers this notification as well.

These are minor things, but I think they would improve the experience for casual users.

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
I like this feature idea, I also find it a big noisy. Will look into trimming it down by default. Thanks for opening an issue!

**Comment by kadisonm** [comment]
Hi sorry I should have been more specific. I wrote that pretty late. I meant 2 notifications like you said. 
Thank you for working on this plugin, it's a good upgrade from the original. I especially like the last synced on the status bar.

**Comment by sboesen** [comment]
Closed as discussed in #18 we will just have this in the status bar except on mobile.
