### ISSUE TITLE
[Bug]: Status bar info error when reload obsidian.

### ISSUE THREAD

**Issue by YIRU69** [sboesen/remotely-secure#17]
### What happened?

1. the status bar `synced 1 days ago`
2. manual sync, and the status bar `synced less than a minute ago`
3. reload obsidian, the status bar `synced 1 days ago`

### What OS are you using?

Windows

### What remote cloud services are you using?

S3

### Version of the plugin

4.9

### Version of Obsidian

1.4.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
I've noticed this, too - will investigate.

**Comment by sboesen** [comment]
Should be fixed in 0.4.12, please reopen if it still occurs
