### ISSUE TITLE
[Feature Request]: Beautify status bar

### ISSUE THREAD

**Issue by YIRU69** [sboesen/remotely-secure#18]
### What feature are you suggesting?

1. The `synced xxx` change to a emoji or svg image, When syncing now, the image can turn round and round. When synced, then the statua bar show it check. And hove the status bar can show the synced time.
2. If it can be a achieve, the progress bar need not to add. #12 

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by YIRU69** [comment]
It also can solve the issue. #15

**Comment by sboesen** [comment]
I like this idea. The notifications are a bit obtrusive in general, but the status bar doesn't show up for mobile so I think we can keep them for mobile.

>If it can be a achieve, the progress bar need not to add. https://github.com/sboesen/remotely-secure/issues/12

I think we'll still want a sort of progress bar, but I think we can put this in the status bar during sync. 

Maybe "Syncing (1/300)" or something like that.

**Comment by sboesen** [comment]
Added in bb1a454 - kept status as text for now, please reopen if this isn't what you were thinking and we can discuss!

**Comment by kadisonm** [comment]
This sounds like a good idea, I'd prefer notifications to be only mobile as well.

**Comment by YIRU69** [comment]
> kept status as text for now, please reopen if this isn't what you were thinking and we can discuss!

It looks good. When  the plugin prepare and it show `preparing`. But when plugin is working, may we can realize the plugin is working. And you said you can put this in the status bar during sync. That sound good. Let us put it on the plugin working alright.

**Comment by YIRU69** [comment]
By the way, the 4.9 4.10 version, I can't find `bookmark  sync` setting and `Syncing (1/300)` status bar. Do I need to delete the plugin and reinstall the plugin?

**Comment by sboesen** [comment]
Bookmark sync is not a setting, it is always on (for now). Is turning it off a feature you're interested in? I assume most people using Obdiain bookmarks want it synced.

Attached is the syncing progress I see - please let me know if you don't see this. For my small vault it happens very quickly so it can be easy to miss.
<img width="106" alt="Screenshot 2023-11-16 at 12 43 42 AM" src="https://github.com/sboesen/remotely-secure/assets/248703/f67fcd1a-a823-41f5-96ea-0a847c0bab57">

**Comment by YIRU69** [comment]
Ok. No problem.
