### ISSUE TITLE
[Bug]: 无法鉴权

### ISSUE THREAD

**Issue by NewTypo** [sboesen/remotely-secure#2]
### What happened?

OneDrive个人版：无法鉴权
![image](https://github.com/sboesen/remotely-secure/assets/17538796/fe123d91-559f-4f60-8390-6fe16483b1d3)

app.js:1 Obsidian Developer Console
plugin:obsidian-markdown-furigana:93 loading Markdown Furigana plugin
app.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at e.printHotkeyForCommand (app.js:1:1096737)
    at t.<anonymous> (app.js:1:1295494)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at app.js:1:236048
    at new Promise (<anonymous>)
    at v (app.js:1:235793)
    at t.onOpen (app.js:1:1295291)
    at t.<anonymous> (app.js:1:1287590)
    at app.js:1:237027
plugin:longform:37647 [Longform] Starting Longform 2.0.4…
plugin:obsidian-outliner:3317 Loading obsidian-outliner
plugin:obsidian-weread-plugin:2 load weread plugin
plugin:obsidian-weread-plugin:2 --------init cookie------ Array(10)
plugin:obsidian-weread-plugin:2 [weread plugin] setting user vid=> 8671170
plugin:obsidian-weread-plugin:2 [weread plugin] setting user name=> 考槃
plugin:table-editor-obsidian:28663 loading markdown-table-editor plugin
plugin:dataview:20020 Dataview: version 0.5.64 (requires obsidian 0.13.11)
plugin:note-refactor-obsidian:6572 Loading Note Refactor plugin
plugin:quickadd:19504 Loading QuickAdd
plugin:quickadd:17504 QuickAdd: (LOG) No migrations to run.
plugin:obsidian42-brat:1970 loading Obsidian42 - BRAT
plugin:attachment-management:1840 Plugin loading: Attachment Management v.0.8.4
plugin:card-board:1 loading CardBoard plugin
plugin:webpage-html-export:57369 loading webpage-html-export plugin
raw.githubusercontent.com/KosmosisDire/obsidian-webpage-export/master/manifest.json?cache=1699329055057:1     Failed to load resource: net::ERR_ADDRESS_INVALID
plugin:webpage-html-export:57451 Could not check for update
plugin:webpage-html-export:56733 Error while minifying CSS file.: 
 Error: Parse Error: <"]:checked,
li[data-task="<"]>input:checked,
li[data-task="<"]>p>input:checked,
input[data-task=">"]:checked,
li[data-task=">"]>input:checked,
li[data-task=">"]>p>input:checked,
input[data-task="d"]:checked,
li[data-task="d"]>input:checked,
li[data-task="d"]>p>input:checked,
input[data-task="u"]:checked,
li[data-task="u"]>input:checked,
li[data-task="u"]>p>input:checked,
input[data-task="S"]:checked,
li[data-task="S"]>input:checked,
li[data-task="S"]>p>input:checked,
input[data-task="“"]:checked,
li[data-task="“"]>input:checked,
li[data-task="“"]>p>input:checked,
input[data-task="c"]:checked,
li[data-task="c"]>input:checked,
li[data-task="c"]>p>input:checked,
input[data-task="p"]:checked,
li[data-task="p"]>input:checked,
li[data-task="p"]>p>input:checked,
input[data-task="n"]:checked,
li[data-task="n"]>input:checked,
li[data-task="n"]>p>input:checked,
input[data-task="b"]:checked,
li[data-task="b"]>input:checked,
li[data-task="b"]>p>input:checked,
input[data-task="-"]:checked,
li[data-task="-"]>input:checked,
li[data-task="-"]>p>input:checked,
input[data-task="l"]:checked,
li[data-task="l"]>input:checked,
li[data-task="l"]>p>input:checked,
input[data-task="I"]:checked,
li[data-task="I"]>input:checked,
li[data-task="I"]>p>input:checked,
input[data-task="/"]:checked,
li[data-task="/"]>input:checked,
li[data-task="/"]>p>input:checked,
input[data-task="i"]:checked,
li[data-task="i"]>input:checked,
li[data-task="i"]>p>input:checked,
input[data-task="*"]:checked,
li[data-task="*"]>input:checked,
li[data-task="*"]>p>input:checked,
input[data-task="?"]:checked,
li[data-task="?"]>input:checked,
li[data-task="?"]>p>input:checked,
input[data-task="!"]:checked,
li[data-task="!"]>input:checked,
li[data-task="!"]>p>input:checked {
    --checkbox-marker-color: transparent;
    border: none;
    border-radius: 0;
    background-image: none;
    background-color: currentColor;
    -webkit-mask-size: var(--checkbox-icon);
    -webkit-mask-position: 50% 50%
}

input[data-task="!"]:checked,
li[data-task="!"]>input:checked,
li[data-task="!"]>p>input:checked {
    --checkbox-color-hover: var(--color-orange);
    color: var(--color-orange);
    -webkit-mask-image: url('data:image/svg+xml;utf8,	vwzkzukp0zp12vwzkzukp0zp	<svg id="svg0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><defs><style>.cls-1{fill:none;}.cls-2{fill-rule:evenodd;}</style></defs><rect class="cls-1" width="16" height="16"/><path class="cls-2" d="M8,16c4.42,0,8-3.58,8-8S12.42,0,8,0,0,3.58,0,8s3.58,8,8,8ZM6.07,3.55c-.08,.29-.09,.6-.03,.9l.86,4.56c.05,.28,.2,.52,.42,.7,.22,.18,.49,.28,.77,.28s.55-.1,.77-.28c.22-.18,.36-.43,.42-.7l.86-4.56c.06-.3,.04-.61-.03-.9-.08-.29-.22-.57-.41-.8-.19-.23-.44-.42-.71-.55-.28-.13-.58-.2-.88-.2s-.61,.07-.88,.2c-.28,.13-.52,.32-.71,.55-.19,.23-.34,.51-.41,.8Zm3.07,10.01c.28-.28,.44-.66,.44-1.06s-.16-.78-.44-1.06c-.28-.28-.66-.44-1.06-.44s-.78,.16-1.06,.44c-.28,.28-.44,.66-.44,1.06s.16,.78,.44,1.06c.28,.28,.66,.44,1.06,.44s.78-.16,1.06-.44Z"/></svg>');
}

input[data-task="?"]:checked,
li[data-task="?"]>input:checked,
li[data-task="?"]>p>input:checked {
    --checkbox-color-hover: var(--color-pink);
    color: var(--color-pink);
    -webkit-mask-image: url('data:image/svg+xml;utf8,	vwzkzukp0zp13vwzkzukp0zp	<svg id="svg0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><defs><style>.cls-1{fill:none;}.cls-2{fill-rule:evenodd;}</style></defs><rect class="cls-1" width="16" height="16"/><path class="cls-2" d="M8,16c4.42,0,8-3.58,8-8S12.42,0,8,0,0,3.58,0,8s3.58,8,8,8ZM4.84,3.66c-.32,.48-.09,1.14,.44,1.37,.23,.1,.49,.1,.72,0,.17-.07,.31-.18,.41-.34,.31-.49,.82-.89,1.6-.89,1.72,0,2.06,1.61,1.45,2.47-.36,.51-.87,.91-1.33,1.37-.28,.28-.55,.58-.74,.93-.19,.33-.27,.69-.31,1.03-.04,.31,.08,.59,.28,.79,.18,.18,.43,.29,.71,.29,.49,0,.89-.38,.95-.87,.04-.3,.1-.45,.2-.63,.41-.76,1.18-1.12,1.98-2.3,.72-1.07,.45-2.5-.02-3.27-.55-.89-1.62-1.61-3.19-1.61-1.43,0-2.51,.7-3.15,1.66Zm3.16,11.01c.73,0,1.33-.6,1.33-1.33s-.6-1.33-1.33-1.33-1.33,.6-1.33,1.33,.6,1.33,1.33,1.33Z"/></svg>');
}

input[data-task="*"]:checked,
li[data-task="*"]>input:checked,
li[data-task="*"]>p>input:checked {
    --checkbox-color-hover: var(--color-yellow);
    color: var(--color-yellow);
    -webkit-mask-image: url('data:image/svg+xml;utf8,	vwzkzukp0zp14vwzkzukp0zp	<svg id="svg0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><defs><style>.cls-1{fill:none;}</style></defs><rect class="cls-1" width="16" height="16"/><path d="M8.91,.58c-.08-.17-.21-.32-.37-.42C8.38,.05,8.19,0,8,0s-.38,.05-.54,.16c-.16,.1-.29,.25-.37,.42l-1.93,4.12L.85,5.36c-.18,.03-.35,.1-.49,.22-.14,.12-.25,.27-.3,.45-.06,.17-.07,.36-.03,.54,.04,.18,.13,.34,.26,.48l3.15,3.23-.75,4.57c-.03,.19,0,.38,.06,.55,.07,.17,.19,.32,.35,.43,.15,.11,.33,.17,.52,.18,.19,0,.37-.03,.54-.12l3.84-2.13,3.84,2.13c.16,.09,.35,.13,.54,.12,.19-.01,.37-.07,.52-.18,.15-.11,.27-.26,.35-.43,.07-.17,.09-.36,.06-.55l-.75-4.57,3.15-3.23c.13-.13,.22-.3,.26-.48,.04-.18,.03-.37-.03-.54-.06-.17-.16-.33-.3
error @ plugin:webpage-html-export:56733
plugin:webpage-html-export:56640 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'view')
    at Object._reportError (plugin:webpage-html-export:56640:23)
    at Object.error (plugin:webpage-html-export:56734:22)
    at _AssetHandler.minifyJSorCSS (plugin:webpage-html-export:55766:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _AssetHandler.updateAssetCache (plugin:webpage-html-export:55822:26)
plugin:cm-chs-patch:7 Jieba loaded
plugin:cm-chs-patch:7 editor word splitting patched
plugin:nl-fast-image-cleaner:567 Fast file Cleaner plugin loaded...
plugin:obsidian-tasks-plugin:289 loading plugin "tasks"
plugin:obsidian-excalidraw-plugin:79 Initialized Excalidraw Image Cache
plugin:dataview:12759 Dataview: all 823 files have been indexed in 1.913s (823 cached, 0 skipped).
plugin:commentator:8 commentator: database load: 2139.44677734375 ms
plugin:commentator:8 commentator: syncing database: 5.7939453125 ms
plugin:longform:35996 [Longform] Loaded and watching projects. Found 2 drafts in 9.431s.
plugin:excalibrain:1 ExcaliBrain indexed 1721 URLs from 165 unique hosts in 120 of 823 markdown files in 15.1 seconds
7VM268 plugin:remotely-secure:53 Uncaught (in promise) ClientConfigurationError: empty_url_error: URL was empty or null.
    at e [as constructor] (plugin:remotely-secure:53:52965)
    at e [as constructor] (plugin:remotely-secure:53:62298)
    at new e (plugin:remotely-secure:53:76448)
    at e.createUrlEmptyError (plugin:remotely-secure:53:77222)
    at new t (plugin:remotely-secure:53:122232)
    at t.transformCIAMAuthority (plugin:remotely-secure:57:2266)
    at Function.eval (plugin:remotely-secure:57:2833)
    at h (plugin:remotely-secure:53:45310)
    at Object.eval [as next] (plugin:remotely-secure:53:44614)
    at eval (plugin:remotely-secure:53:44340)
    at new Promise (<anonymous>)
    at lt (plugin:remotely-secure:53:44137)
    at t.createDiscoveredInstance (plugin:remotely-secure:57:2665)
    at EE.createAuthority (plugin:remotely-secure:68:21968)
    at EE.buildOauthClientConfiguration (plugin:remotely-secure:68:19557)
    at EE.getAuthCodeUrl (plugin:remotely-secure:68:16518)
    at async qie (plugin:remotely-secure:68:26998)
    at async gT.onOpen (plugin:remotely-secure:111:1741)
2plugin:remotely-secure:30 Uncaught (in promise) Error: A client id is required. You can set the client id using .setClientId().
    at F.value (plugin:remotely-secure:30:44023)
    at Cee (plugin:remotely-secure:53:37127)
    at mT.onOpen (plugin:remotely-secure:109:1624)
    at e.open (app.js:1:1309979)
    at eval (plugin:remotely-secure:114:7333)
    at HTMLButtonElement.<anonymous> (app.js:1:1318112)
5plugin:remotely-secure:53 Uncaught (in promise) ClientConfigurationError: empty_url_error: URL was empty or null.
    at e [as constructor] (plugin:remotely-secure:53:52965)
    at e [as constructor] (plugin:remotely-secure:53:62298)
    at new e (plugin:remotely-secure:53:76448)
    at e.createUrlEmptyError (plugin:remotely-secure:53:77222)
    at new t (plugin:remotely-secure:53:122232)
    at t.transformCIAMAuthority (plugin:remotely-secure:57:2266)
    at Function.eval (plugin:remotely-secure:57:2833)
    at h (plugin:remotely-secure:53:45310)
    at Object.eval [as next] (plugin:remotely-secure:53:44614)
    at eval (plugin:remotely-secure:53:44340)
    at new Promise (<anonymous>)
    at lt (plugin:remotely-secure:53:44137)
    at t.createDiscoveredInstance (plugin:remotely-secure:57:2665)
    at EE.createAuthority (plugin:remotely-secure:68:21968)
    at EE.buildOauthClientConfiguration (plugin:remotely-secure:68:19557)
    at EE.getAuthCodeUrl (plugin:remotely-secure:68:16518)
    at async qie (plugin:remotely-secure:68:26998)
    at async gT.onOpen (plugin:remotely-secure:111:1741)

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.4.1

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Hello, thank you for the bug report.

Looks like I need to register a client application with onedrive as this uses oauth code flow. Will update this for the next official release, sorry about that.

**Comment by NewTypo** [comment]
> Hello, thank you for the bug report.
> 
> Looks like I need to register a client application with onedrive as this uses oauth code flow. Will update this for the next official release, sorry about that.

Thank you for your contribution to Obsidian.
