### ISSUE TITLE
[Bug]: Sync on save triggering ‘Running in stage’ notification

### ISSUE THREAD

**Issue by kadisonm** [sboesen/remotely-secure#21]
### What happened?

Exactly what the title says. Maybe disable the notification if it is caused by sync on save and only have it show if it’s a manual sync.

Everything else is working perfectly in the plugin as far as I can tell. Glad I switched to this one.

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.4.11

### Version of Obsidian

1.4.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Fixed in 0.4.12
