### ISSUE TITLE
[Bug]: Error: password_not_matched

### ISSUE THREAD

**Issue by YayoAstur** [sboesen/remotely-secure#22]
### What happened?

Hi.
I just migrated from Remotely Save but Im not able to make it work as Im getting _Error: password_not_matched_  while trying to sync. I've been using Dropbox, but also tried OneDrive, I've already tried reseting the password, clearing plugin data, all that stuff...

Looking at the console the full error message is:
_remotely-secure-1700174485864: abort sync, triggerSource=manual, error while checking_password_

Im running out of ideas... Any clue on what its making me getting this error?

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal, Dropbox

### Version of the plugin

0.4.12

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Hello, sorry to hear this - I think this may be a duplicate issue of #20. Please try the latest version and open settings -> remotely secure -> set enable debug info from "false" to "true" and check the console logs after synchronizing.

**Comment by sboesen** [comment]
@YayoAstur Please try the latest version and reopen this issue if it still occurs.
