### ISSUE TITLE
[Bug]: Cannot sync from my Android phone or my iPad

### ISSUE THREAD

**Issue by cathodeyolk** [sboesen/remotely-secure#24]
### What happened?

Hey! I can't seem to sync with my OneDrive from either my Android phone or my iPad. Syncing from my desktop PC with the plugin seems to works fine though.

Repro:
1. Create a new empty vault with the same name as my remote vault;
2. Install Remotely Secure, go to settings;
3. Choose OneDrive for personal as a cloud service provider;
4. Click on Auth, go through the link, log in to my account in the browser, go back to Obsidian;
5. The plugin says the connection was successful;
6. Click on "Check Connectivity" to be sure, result: "Great! We can connect to OneDrive";
7. Go back to the vault, open the sandwich menu from the bottom of the screen, click on "Remotely Secure" to start manual sync;
8. Get the error messages shown below:

![photo_2023-11-17_18-09-05](https://github.com/sboesen/remotely-secure/assets/10135462/6a47aed2-6739-4af6-a9ae-955c3481b277)

Could it be because of my Two-Factor authentication? I'm using 6-digit tokens as an additional security measure.

### What OS are you using?

Android

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.4.15

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by YIRU69** [comment]
Hi check it! https://github.com/sboesen/remotely-secure/issues/4

**Comment by sboesen** [comment]
Thanks @YIRU69, agreed it looks like that same issue occurring here. I think this could happen if you synced before updating  (which wouldn't create the manifest file) and then synced after.

@cathodeyolk could you please make sure you have a backup and then delete the OneDrive folder and try again? It shouldn't continue occurring (and multi factor shouldn't be a problem, either).

Sorry you're running into sync issues here!

**Comment by cathodeyolk** [comment]
@sboesen @YIRU69  Got it working, thank you!
- Did a backup, then deleted my vault folder from OneDrive
- Opened Obsidian app on my Android phone
- Went to Remotely Secure plugin settings, checked Auth data is still good
- Started manual Sync, and got the manifest file created in the empty vault folder!
- Copied my vault files from the backup, started the sync
- Now I have my vault synced across devices yay

**Comment by sboesen** [comment]
Awesome, glad to hear!
