### ISSUE TITLE
[Feature Request]: Refactor syncRun

### ISSUE THREAD

**Issue by sboesen** [sboesen/remotely-secure#27]
### What feature are you suggesting?

So that we can enable sync on save to scan the folder some refactoring would be helpful. Currently it's difficult to do without duplicating code in syncRun. 

I'd like to refactor `syncRun` and break it down into a class, say `Synchronize`, with each sync step being a method call (or a few if it makes sense). That was we can call getSyncPlan() without having to duplicate the sync logic up to that step, and use that to perform a quick scan and check the mtimeLocal vs mtimeRemote to determine if a sync is needed.

I think it will also help make the synchronization process much more readable.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by MikeWi11s0n** [comment]
+1

**Comment by sboesen** [comment]
Could be better, but the usage described is doable using the partial refactor. Closing.
