### ISSUE TITLE
[Feature Request]: Sync Status Bar (希望能增加一些同步功能，添加一个状态栏显示)

### ISSUE THREAD

**Issue by YIRU69** [sboesen/remotely-secure#3]
### What feature are you suggesting?

终于有大佬来更新这个插件了，在查看了最新的官方插件更新中发现了，真的很感谢你

rs这个插件我一直用了好久，但是随着版本的更新，以及原作者的不维护，有很多问题，我能力不足，终于看到有人能去解决了

中文论坛也有人去更新这个插件，https://forum-zh.obsidian.md/t/topic/18940/12 

我希望大佬可以看看这个人的更新，把同步更新的策略和状态显示能并入进来，最后再次感谢大佬

### What remote cloud services are you using, or suggesting adding the feature to?

S3

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Hello, thanks for the link!

It looks like the two updates are sync status bar and sync-on-save. We currently have sync-on-save via @sampurkiszb, could you confirm if this meets your needs?

I will look into adding @Drumber's [code changes](https://github.com/remotely-save/remotely-save/pull/168/files) into the project once the bugs from forking/updating are corrected. Thanks again!

**Comment by YIRU69** [comment]
yeah, I find it add a syn-on-save. So I hope it can add the sync status bar. Thank you.

**Comment by sboesen** [comment]
Of course, no problem! I like the status bar, will definitely use that with credit. Prioritizing fixing the bugs currently but if anyone wants to take a stab at it for now feel free to open a PR.

**Comment by sboesen** [comment]
Added in release 0.4.5! I added [placeholder translations](https://github.com/sboesen/langs/commit/23d16057d28e362da41ea701ca88bf8e72462714) in english for zh_cn and zh_tw, please feel free to open a pull request if you want those updated.
