### ISSUE TITLE
[Feature Request]: The ability for faster automatic synchronization

### ISSUE THREAD

**Issue by MartinJDavis93** [sboesen/remotely-secure#33]
### What feature are you suggesting?

Since I mentioned in the last issue that I wrote two issues for Remotely Save, I decided to duplicate them here as well, given that you are planning development for your fork.

Currently, the minimum setting for automatic synchronization can be set to 1 minute. This is not very convenient. It would be great if you could enable the option to reduce this time. From my empirical observations, automatic synchronization, whether triggered manually or not, never takes more than 5 seconds. If you could add an option for automatic synchronization every 5 seconds, it would be almost real-time synchronization. The only potential issue could be frequent requests to the cloud service, but it shouldn't be a significant problem. If you consider 5 seconds to be too fast and potentially problematic, you could consider extending it to 10-15 seconds, although, in my opinion, 5 seconds would be more preferable. Additionally, you could offer several options, such as 5, 15, 30 seconds, and then the current 1 minute setting. That would be simply fantastic. I hope you will consider my suggestion.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Thanks for filing this one - I'll definitely look at adding this, I don't disagree with the usefulness of shorter sync options. For what it's worth, have you considered enabling sync on save? It should be more responsive than auto-sync and can sync every second if you'd like: 
<img width="800" alt="Screenshot 2023-11-23 at 2 09 33 PM" src="https://github.com/sboesen/remotely-secure/assets/248703/5711b268-169b-4c94-8d64-8ef600fd4182">


I believe lower automatic sync options were added in [another fork](https://github.com/sboesen/remotely-secure/issues/3#issuecomment-1806767958) and I should be able to port the changes easily if I'm not able to figure it out easily.

**Comment by sboesen** [comment]
Added in 0.4.18, thanks for the suggestion!

**Comment by MartinJDavis93** [comment]
> Thanks for filing this one - I'll definitely look at adding this, I don't disagree with the usefulness of shorter sync options. For what it's worth, have you considered enabling sync on save? It should be more responsive than auto-sync and can sync every second if you'd like: <img alt="Screenshot 2023-11-23 at 2 09 33 PM" width="800" src="https://user-images.githubusercontent.com/248703/285316311-5711b268-169b-4c94-8d64-8ef600fd4182.png">
> 
> I believe lower automatic sync options were added in [another fork](https://github.com/sboesen/remotely-secure/issues/3#issuecomment-1806767958) and I should be able to port the changes easily if I'm not able to figure it out easily.

Oh, that's great. I've already tried it, and everything works perfectly. I didn't see the 'Sync on Save' option in the settings yesterday, so I wasn't aware of it at all. I noticed it today while going through the plugin settings. Despite having 'Sync on Save', I think the ability to set a shorter time for automatic synchronization is also excellent. For now, I've enabled both options and haven't encountered any issues. Automatic synchronization is just so straightforward and clear. Just automatic synchronization, now with the option to set shorter intervals between syncs. As for 'Sync on Save', judging by the description, it tracks changes in the file and similar things, which theoretically could break if Obsidian developers decide to make changes in this regard. Therefore, automatic synchronization in this regard is more versatile and resilient. Especially since its implementation didn't seem to pose difficulties, considering how quickly it was introduced.

**Comment by sboesen** [comment]
Great, glad to hear it's working well for you. I plan to make some changes to Sync on Save to improve its robustness as I believe there are conditions (such as editing a file and then opening another quickly) which could bypass sync on save. Definitely doesn't hurt to have both enabled until then or after. Thanks again for filing!

**Comment by MartinJDavis93** [comment]
> Great, glad to hear it's working well for you. I plan to make some changes to Sync on Save to improve its robustness as I believe there are conditions (such as editing a file and then opening another quickly) which could bypass sync on save. Definitely doesn't hurt to have both enabled until then or after. Thanks again for filing!

Thank you for such a prompt response.

**Comment by sboesen** [comment]
No problem at all! Happy to help - fwiw I am tracking the update to sync on save [here](https://github.com/sboesen/remotely-secure/issues/26#issuecomment-1818001115).
