### ISSUE TITLE
[Bug]: Obsidian 的安卓端无法启用插件

### ISSUE THREAD

**Issue by Booting-O** [sboesen/remotely-secure#6]
### What happened?

我在 macOS 平台和 Windows 平台的 Obsidian 都可以正常开启此插件，在安卓端可以安装，但是无法启用。
另一款插件 remotely save 可以在安卓端启用

### What OS are you using?

Android

### What remote cloud services are you using?

S3, webdav

### Version of the plugin

0.4.1

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Thank you, I need to test this on my Android device. Unfortunately it's also not working on mobile for iOS and I think it was related to the changes required to update the app / pass the Obsidian team's review.

If anyone can post a stack trace with the latest build on Android that will help track down what is going wrong, this is one of my highest priorities.

**Comment by KuiyueRO** [comment]
> Thank you, I need to test this on my Android device. Unfortunately it's also not working on mobile for iOS and I think it was related to the changes required to update the app / pass the Obsidian team's review.谢谢，我需要在我的安卓设备上测试一下。不幸的是，它在 iOS 移动设备上也无法运行，我认为这与更新应用程序/通过黑曜石团队审核所需的更改有关。
> 
> If anyone can post a stack trace with the latest build on Android that will help track down what is going wrong, this is one of my highest priorities.如果有人能提供 Android 最新版本的堆栈跟踪，这将有助于找出问题所在，这也是我的首要任务之一。

```
Plugin failure: remotely-secure TypeError: Cannot read properties of undefined (reading 'lstatSync')
    at anonymous (plugin:remotely-secure:94:21937)
    at e.<anonymous> (app.js:1:2018681)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at a (app.js:1:235850)
（匿名） @ app.js:1
（匿名） @ app.js:1
（匿名） @ app.js:1
s @ app.js:1
Promise.then（异步）
l @ app.js:1
（匿名） @ app.js:1
v @ app.js:1
e.enablePlugin @ app.js:1
（匿名） @ app.js:1
（匿名） @ app.js:1
（匿名） @ app.js:1
（匿名） @ app.js:1
v @ app.js:1
e.enablePluginAndSave @ app.js:1
（匿名） @ app.js:1
（匿名） @ app.js:1
（匿名） @ app.js:1
（匿名） @ app.js:1
v @ app.js:1
（匿名） @ app.js:1
t.setValue @ app.js:1
t.onClick @ app.js:1
```

**Comment by sboesen** [comment]
Thank you for sharing that, unfortunately it's difficult to read as this is the production build which is minified.

I've uploaded a development copy [here](https://github.com/sboesen/remotely-secure/releases/tag/0.4.1-dev), will take a look on my own device when I get a chance. Any pull requests welcome, too.

**Comment by KuiyueRO** [comment]
Not working on 0.4.1.

```
// node_modules/@aws-sdk/lib-storage/dist-es/runtimeConfig.js

var ClientDefaultValues = **assign2(**assign2({}, ClientSharedValues), { runtime: "node", lstatSync: import_fs.lstatSync });
```

**Comment by KuiyueRO** [comment]
```
if (import_fs && import_fs.lstatSync) {
  var ClientDefaultValues = __assign2(__assign2({}, ClientSharedValues), {
    runtime: "node",
    lstatSync: import_fs.lstatSync
  });
} else {
}
```

This can be enabled on mobile, but none of my devices can link to the s3 bucket right now, so I don't know what problems it will cause.

**Comment by sboesen** [comment]
I believe updating that `@aws-sdk/lib-storage` fixed this, thank you for posting that code snippet! Will continue testing to make sure it is compatible but I can now activate it on iOS.

**Comment by eric-pierce** [comment]
@sboesen from your perspective should we be good to use this on iOS with webdav, or are there still compatibility issues not present in remotely-save?

**Comment by sboesen** [comment]
@eric-pierce I have not tested webdav but I didn't change anything apart RE webdav specifically, just removed some [commented out code](https://github.com/sboesen/remotely-secure/commit/5491fd0f62b5b9ac444f58065e60441408be61ce#diff-d4d1695f144f84312b16e914f41697be30877f1c9914a6dbaa8ee248fa6209f4)

If it doesn't work for you please open a bug report! Thanks.

**Comment by sboesen** [comment]
Resolving this issue; please re-open if you're still unable to activate the plugin on mobile.
