### ISSUE TITLE
[Bug]: OneDrive Auth modal not working on Mobile (iOS)

### ISSUE THREAD

**Issue by sboesen** [sboesen/remotely-secure#8]
### What happened?

The modal pops up when I click "Auth" but it doesn't include a link to actually authN with OneDrive.

### What OS are you using?

iOS (iPhone, iPad)

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.4.2

### Version of Obsidian

1.4.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by The-Ducktor** [comment]
same issue on android

**Comment by sboesen** [comment]
It looks like the modal contents are pushed off the screen. For what it's worth the modal displays correctly for the Dropbox flow, so I think this should be an easy fix 🤞

**Comment by sboesen** [comment]
I tried to shorten the description before the URL is displayed to match the length of text in the Dropbox modal and that didn't do the trick (see 0.4.8). I think something on mobile is preventing it from loading any text into the modal at all. More investigation is required.

**Comment by kadisonm** [comment]
Can also confirm this is happening to me. 
IOS 17.03 iPhone 11 Pro

Is there an alternative to get the auth link for now?

**Comment by sboesen** [comment]
Here is the error it looks like I'm seeing on mobile, likely the reason OneDrive is the only one broken:

```
Uncaught (in promise) ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://undefined/common/v2.0/.well-known/openid-configuration
    at e [as constructor] (plugin:remotely-secure:49:52821)
    at new e (plugin:remotely-secure:49:62154)
    at e.createEndpointDiscoveryIncompleteError (plugin:remotely-secure:49:62837)
    at Function.eval (plugin:remotely-secure:53:3081)
    at d (plugin:remotely-secure:49:45170)
    at Object.eval [as throw] (plugin:remotely-secure:49:44474)
    at d (plugin:remotely-secure:49:44104)
```

Will need to investigate further. Not sure why it is working on Desktop but getting an invalid authority (my assumption based on error message & `undefined` in URL) on mobile. Something is odd

**Comment by sboesen** [comment]
Tested on iOS, looks like it's working now! Was able to auth and sync, but didn't test much beyond that. Please open a new bug if sync isn't working (or reopen this one if the modal is broken still for you).

**Comment by kadisonm** [comment]
It’s working now. Thanks so much for the quick fix.

**Comment by sboesen** [comment]
No problem!
